### ISSUE TITLE
[Windows 7 doesn't support WebSocket.dll] "simple" sample result in a RelayException

### ISSUE THREAD

**Issue by pmhsfelix** [Azure/azure-relay-dotnet#32] opened 2016-12-03 00:23 UTC
I'm trying out the "simple" sample and when I run the server I get a `RelayException` with an inner exception stating `The remote server returned an error: (500) Internal Server Error.` All the four parameters (namespace, endpoint path, policy name and policy key seem to be ok - if I change any of them the error is and appropriate for the change.

**Comment by dstuckims** [comment] 2016-12-05 18:52
Will you include the full output of RelayException.ToString()?  (Ideally that would have a TrackingId, Timestamp, and include the address, i.e. "sb://YOURNAMESPACE.servicebus.windows.net/YOURENDPOINT").

**Comment by pmhsfelix** [comment] 2016-12-05 19:15
InternalServerError. TrackingId:076fd61e-e290-4ce8-8943-1092806c95f0_G26, SystemTracker:sb://pmhsfelix.servicebus.windows.net/hybrid0, Timestamp:12/5/2016 7:14:20 PM

**Comment by pmhsfelix** [comment] 2016-12-05 22:14
I didn't managed to build the "simple" sample directly due to the problem reported in #31. I removed the DLL that was being loaded directly from a "strange" path and installed Microsoft.Azure.Relay 0.1.2-preview.

Here is the content of my `packages.config`
~~~
<packages>
  <package id="Microsoft.Azure.Relay" version="0.1.2-preview" targetFramework="net452" />
</packages>
~~~

**Comment by dstuckims** [comment] 2016-12-05 22:34
- You still get the InternalServerError exception with the latest 0.1.2-preview package?
- Does the exception occur when trying to run the Server.exe?
- What Operating System are you running this on?
- Have you made any code or project changes at all that might affect the behavior?
- Is the sample running as a 32 or 64 bit process?
- Would it be possible for you to reproduce the issue with a debugger attached, stop at the very first first-chance exception after calling listener.OpenAsync(), and get a memory dump of the process?  (In VS go to the Debug Menu -> Save Dump As...)

**Comment by pmhsfelix** [comment] 2016-12-05 23:10
>You still get the InternalServerError exception with the latest 0.1.2-preview package?

Yes
>Does the exception occur when trying to run the Server.exe?

Yes
>What Operating System are you running this on?

Windows 7 Professional SP1
>Have you made any code or project changes at all that might affect the behavior?

No
>Is the sample running as a 32 or 64 bit process?

Build is set to "Any CPU"
>Would it be possible for you to reproduce the issue with a debugger attached, stop at the very first first-chance exception after calling listener.OpenAsync(), and get a memory dump of the process? (In VS go to the Debug Menu -> Save Dump As...) I can give you a hybrid connection and keyname/keyvalue pair if you'd like. Contact me at dstucki (at) microsoft.com if you want me to do this.

I've the memory dump and it's ~160MB. What's the best way to send it to you?

**Comment by dstuckims** [comment] 2016-12-05 23:17
This is most likely a Windows 7 compatibility issue then.  I need to do some investigation to into this.

**Comment by dstuckims** [comment] 2016-12-06 01:21
At this point we don't really support Windows 7.  We're building on top of the .NET 4.5 System.Net.WebSockets.ClientWebSocket which also doesn't support Windows 7 (websocket.dll support from the OS is not there).

However, you may be able to get something working on your own by doing something like this example branch/commit:
Branch: https://github.com/dstuckims/azure-relay-dotnet/tree/PossibleWorkAroundForWindows7
Commit: https://github.com/dstuckims/azure-relay-dotnet/commit/ab4628939d6aba0c5904005e839ec62e04b2647f

I took the ManagedWebSocket class from .NET Core (they actually only use this implementation on *nix) and hacked it to build with .NET 4.5 (and simply removed the .NET Core build for the mean time, I wasn't trying to make it cross-compile for all platforms).  This hasn't been tested but you may be able to take this example branch/commit, build your own copy of Microsoft.Azure.Relay.dll and get it to work on Windows 7 (you'll probably want to change the signing key and turn off delay signing on the library you build since it's not coming from Microsoft build labs).  This is very unofficial at this point but I'm sharing it in case it might help.

**Comment by dstuckims** [comment] 2016-12-06 21:50
I have now tried the approach I mentioned above with the changes in that private branch of mine.  

1. I built a new Microsoft.Azure.Relay.dll with those changes in https://github.com/dstuckims/azure-relay-dotnet/commit/ab4628939d6aba0c5904005e839ec62e04b2647f.
2. Updated the Simple sample to reference that newly built Microsoft.Azure.Relay.dll
3. Skipped verification on the Windows 7 machine by adding this registry entry:
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\StrongName\Verification\*,31bf3856ad364e35]
(or you could run sn.exe, something like "sn.exe -Vr Microsoft.Azure.Relay.dll", I believe, but I didn't have sn.exe on that machine at the time).

Then the "simple" sample server.exe and client.exe worked on Windows 7.

**Comment by jburnsman** [comment] 2017-09-10 19:38
Just wanted to confirm I used the method described for updating Microsoft.Azure.Relay.dll, and it successfully worked for using Relay on Windows 7. Thanks

**Comment by jburnsman** [comment] 2017-10-16 02:57
Could this modification in ab4628939d6aba0c5904005e839ec62e04b2647f be ported to the 1.0.0 release of Azure.Relay to allow this to be used on Win7 with a non pre-release version? I have tried myself but have not had any luck getting a clean build yet. Thanks very much

**Comment by dlstucki** [comment] 2020-01-08 19:06
[Windows 7 support will end on January 14, 2020](https://support.microsoft.com/en-us/help/4057281/windows-7-support-will-end-on-january-14-2020)

Closing as won't fix.

**Closed by dlstucki** 2020-01-08 19:06 UTC
Labels: Feature Request, Question, Relay, customer-reported

**Comment by gdalsnes** [comment] 2020-09-08 21:37
Beating a dead horse? But 2.0..1 works fine on Windows 7 as long as using the netstandard2.0 assembly (as it is using managed websockets I assume) while net451 assembly does not work (as it is using native websockets I assume, and you get platform not supported).

**Comment by vany0114** [comment] 2020-11-04 23:21
@jburnsman do you have that dll? I wasn't been able to build that branch
